name: build

on: [push, pull_request]

jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
          CI: true
          PLAID_CLIENT_ID: ${{secrets.plaidClientId }}
          PLAID_SECRET: ${{secrets.secret}}
          PLAID_PUBLIC_KEY: ${{secrets.publicKey}}
          # PLAID_ENV: ${{secrets.plaidEnvironment }}
        with:
          coverageCommand: npm run coverage
          debug: true
